# Default values for alertsnitch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: 
  repository: registry.gitlab.com/yakshaving.art/alertsnitch
  tag: "0.2.1"
  pullPolicy: IfNotPresent

containerPort: 9567

service:
  type: ClusterIP
  port: 9567
  targetPort: 9567

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Health check on creation pod
livenessProbe:
  path: /-/health
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

# Healh check continuos
readinessProbe:
  path: /-/ready
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3


