# https://github.com/helm/charts/tree/master/stable/prometheus-mysql-exporter
replicaCount: 1

image:
  repository: "prom/mysqld-exporter"
  tag: "v0.11.0"

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 9104

serviceMonitor:
  enabled: true
  interval: 1m
  scrapeTimeout: 30s

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

mysql:
  host: "apisuite-v2-roma.cc8tnak52vsg.sa-east-1.rds.amazonaws.com"
  port: 3306
  user: "mysql_exporter"
  existingSecret: false
