mysql:
    pass: ENC[AES256_GCM,data:WlL5+G30QoI=,iv:Et8jijL/SJcDpH263HwLq8fnYIAyOF0O3ky55VhaEk0=,tag:Y41gXK9JfZHaq981vYhh7Q==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:sa-east-1:473412377568:key/ef0ed785-7aba-4057-8a5b-9c53359024a5
        created_at: '2020-02-13T15:54:40Z'
        enc: AQICAHhXpW2JLjAYIWeMfYMVw0Ex1sIVh80ZdJPNd/19lLm8xgFpisYQOViQF8Uu24cl8strAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5pwEzD9Lyvnd40MqAgEQgDuGtNTLhkL1Ybdlp/KwkWsJdwFh2uT3ViPhuTeE0NnMcAG3VN3eE5wOb/8C4LdcwS+jwnJ2MoyHIxoLUQ==
        aws_profile: default
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-02-13T15:54:40Z'
    mac: ENC[AES256_GCM,data:Xh3i3TCuNOWw0WOFDmMGbWkFEdtVJo3wiX5UVS492/IU6exxhSoKPmNQCEcX6Q9swa9/iQV7sSCX4IgCLILDnlZdop1jhJS0JBl5xxpROTTrTjb7COxKFMN+TsGNLMJu36sv98nJI8MXiKzjRn7N/d0j9OifxFCOgG85/2gd3E0=,iv:utVA3N2g7kNmjPaSLvwrsuPJpXsUtQlArkF+SOr9ztY=,tag:uLeQ2s5nFQlq3KO9ct19Ow==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
